project:
  type: website
  resources:
    - CNAME

website:
  title: "MarineSensitivity.org"
  site-url: https://MarineSensitivity.org
  repo-url: https://github.com/MarineSensitivity/MarineSensitivity.github.io
  google-analytics: "G-9HW6L751XG"
  favicon: images/favicon.ico
  twitter-card:
    creator: "@ben_d_best"
    site: "@BOEM"
  open-graph:
    site-name: "MarineSensitivity.org"
  page-footer:
    center: "Sponsored by [Bureau of Ocean Energy Management](https://www.boem.gov/) | Built with [Quarto](https://quarto.org/) | &copy; 2023–2026 [Ben Best](https://bbest.github.io/cv), PhD"

format:
  html:
    theme:
      dark:  [darkly,  styles.scss]
      light: [flatly,  styles.scss]
    toc: false
    page-layout: full
